name: Build Release

on:
  workflow_run:
    workflows: [Android Tests]
    types: [completed]
    branches: [main]

jobs:
  build:
    name: Build APK and Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') && ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        working-directory: ./AndroidProject
        run: chmod +x ./gradlew

      - name: Build APK
        working-directory: ./AndroidProject
        run: ./gradlew assembleDebug

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-debug-apk
          path: AndroidProject/app/build/outputs/apk/debug/app-debug.apk

      - name: Create a new release
        uses: softprops/action-gh-release@v1
        with:
          files: AndroidProject/app/build/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      