name: Android Tests
on:
  push:
    branches:
      - main
      - develop
jobs:
  android-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      # I Need to make gradlew executable
      - name: Make gradlew executable
        working-directory: ./AndroidProject
        run: chmod +x ./gradlew

      # Execute unit tests
      - name: Android units tests
        working-directory: ./AndroidProject
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: ./gradlew clean jacocoTestReport sonarqube

      # Show a report of the unit tests results
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless

  android-ui-tests:
    runs-on: macos-13
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      # I Need to make gradlew executable
      - name: Make gradlew executable
        working-directory: ./AndroidProject
        run: chmod +x ./gradlew

      - name: Android UI tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          working-directory: ./AndroidProject
          profile: pixel_2
          target: google_apis
          disable-animations: true
          emulator-options: -no-window -gpu off -no-snapshot -noaudio -no-boot-anim
          script: ./gradlew connectedCheck

      - name: Android UI tests artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ui-tests-artifacts
          path: ./AndroidProject/app/build/reports/androidTests/connected/
  
  build:
    name: Build APK
    runs-on: ubuntu-latest
    needs: [android-unit-tests, android-ui-tests]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        working-directory: ./AndroidProject
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v3
        with:
          name: app-debug-apk
          path: .

      - name: Create a new release
        uses: softprops/action-gh-release@v1
        with:
          files: app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
